/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/sweta/UGP/coreutils/test-build-afl"
#define EXEC_PREFIX "/home/sweta/UGP/coreutils/test-build-afl"
#define BINDIR "/home/sweta/UGP/coreutils/test-build-afl/bin"
#define SBINDIR "/home/sweta/UGP/coreutils/test-build-afl/sbin"
#define LIBEXECDIR "/home/sweta/UGP/coreutils/test-build-afl/libexec"
#define DATAROOTDIR "/home/sweta/UGP/coreutils/test-build-afl/share"
#define DATADIR "/home/sweta/UGP/coreutils/test-build-afl/share"
#define SYSCONFDIR "/home/sweta/UGP/coreutils/test-build-afl/etc"
#define SHAREDSTATEDIR "/home/sweta/UGP/coreutils/test-build-afl/com"
#define LOCALSTATEDIR "/home/sweta/UGP/coreutils/test-build-afl/var"
#define RUNSTATEDIR "/home/sweta/UGP/coreutils/test-build-afl/var/run"
#define INCLUDEDIR "/home/sweta/UGP/coreutils/test-build-afl/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/sweta/UGP/coreutils/test-build-afl/share/doc/coreutils"
#define INFODIR "/home/sweta/UGP/coreutils/test-build-afl/share/info"
#define HTMLDIR "/home/sweta/UGP/coreutils/test-build-afl/share/doc/coreutils"
#define DVIDIR "/home/sweta/UGP/coreutils/test-build-afl/share/doc/coreutils"
#define PDFDIR "/home/sweta/UGP/coreutils/test-build-afl/share/doc/coreutils"
#define PSDIR "/home/sweta/UGP/coreutils/test-build-afl/share/doc/coreutils"
#define LIBDIR "/home/sweta/UGP/coreutils/test-build-afl/lib"
#define LISPDIR "/home/sweta/UGP/coreutils/test-build-afl/share/emacs/site-lisp"
#define LOCALEDIR "/home/sweta/UGP/coreutils/test-build-afl/share/locale"
#define MANDIR "/home/sweta/UGP/coreutils/test-build-afl/share/man"
#define PKGDATADIR "/home/sweta/UGP/coreutils/test-build-afl/share/coreutils"
#define PKGINCLUDEDIR "/home/sweta/UGP/coreutils/test-build-afl/include/coreutils"
#define PKGLIBDIR "/home/sweta/UGP/coreutils/test-build-afl/lib/coreutils"
#define PKGLIBEXECDIR "/home/sweta/UGP/coreutils/test-build-afl/libexec/coreutils"
